export const constVariable = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    FAILURE: 'failure',
    USERID: 'userId',
    USERNAME: 'username',
    FIRSTNAME: 'firstName',
    LASTNAME: 'lastNAme',
    USERTYPE: 'usertype',
    TOKEN: 'token',
    USER: 'user',
    BEARER: 'Bearer',
    APPLICATION_JSON: 'application/json',
    UNKNOWN_ERROR: 'Unknown error!',
    ADMIN: 'admin',
    SUPERADMIN: 'superAdmin',
    PAGE_NO: 1,
    PAGE_LIMIT: 10,
    ROUTES:{
        PROFILE:'/profile'
    },
    SEARCH_MAX_LENGTH: 2,
    SEARCH_MIN_LENGTH: 0,
    SEARCH_TIMEOUT: 750,
    MODAL_LG_SIZE:'lg',
    MODAL_MD_SIZE:'md',
    MODAL_SM_SIZE:'sm',
    YES_TEXT:'yes',
    NO_TEXT:'no',
    SPINNER: {
        bdColor: "rgba(51,51,51,0.8)",
        size: "medium",
        color: "#fff",
        type: "ball-scale-multiple",
        style: "font-size: 20px, color: white",
        loadingText: "Loading... ",
    },
    REFRESH_TOKEN: 3300000,
    SESSION_EXPIRE: 300000,
    FLAGS: {
        TRUE: true,
        FALSE: false,
        UNDEFINED: undefined,
        UNDEFINED_STRING: 'undefined',
        NULL: null,
        ALL: 'All',
        ARROW_LEFT: 'ArrowLeft',
        ARROW_RIGHT: 'ArrowRight',
        TAB: 'Tab',
        ENTER: 'Enter',
        YES: 'yes',
        NO: 'no',
    },
    HTTP_PARAMS_KEYS: {
        PAGE: 'page',
        LIMIT: 'limit',
        SEARCH: 'search',
        STATUS_ACTIVE: 'Active',
        STATUS_INACTIVE: 'Inactive',
        ORDER_BY: 'orderBy',
        ORDER_BY_ASC: 1,
        ORDER_BY_DESC: -1,
      
    },
    OPENEYE: "assets/images/open-eye.png",
    CROSSEYE: "assets/images/cross-eye.png"
}